### ISSUE TITLE
load_static_elements() does not match assets with relative paths without leading /

### ISSUE THREAD

**Issue by TravisWhitehead** [tag1consulting/goose-eggs#56]
When switching from the old-school umami example to the `goose-eggs` version, I no longer got any requests to static assets. It looks like the issue is due to changes in assumptions made in the regexps used in `load_static_elements()`:
https://github.com/tag1consulting/goose-eggs/blob/827f5ce6489542fd1536d5b3b3276394595187b9/src/lib.rs#L736

Consider an example HTML that has:
```html
<script src="assets/foo/bar.js"></script>
```

This fails to match because it does not have `base_url` or a leading `/`.

I'll note that the site I am testing against also makes use of:
```html
<base href="/howdy/">
```

This is a case that is also not handled here, as the base should be extracted and prepended to the extracted asset path. (`/howdy/assets/foo/bar.js` would be the full path to request).

**Comment by jeremyandrews** [comment]
Reviewed this a bit, the path forward is:

1) Add tests to cover all variations
2) Fix this bug report and be sure we don't regress

**Comment by jeremyandrews** [comment]
@TravisWhitehead Please take a look at https://github.com/tag1consulting/goose-eggs/pull/57 -- it was more effort than I expected to find something that worked. I'm curious if you can think of a simpler/cleaner way to do the same thing.

**Comment by TravisWhitehead** [comment]
> @TravisWhitehead Please take a look at #57 -- it was more effort than I expected to find something that worked. I'm curious if you can think of a simpler/cleaner way to do the same thing.

Yeah, when I (briefly) flirted with fixing this I also found it to be more complicated than I had bargained for. This is cleaner than my first attempt so it looks good to me.
