### ISSUE TITLE
fdsfsdfsdfsd

### ISSUE THREAD

**Issue by michaelemeyers** [tag1consulting/goose-eggs#61]

**Comment by jeremyandrews** [comment]
Unintentional, closing.

**Comment by michaelemeyers** [comment]
Sorry about that I was showing Michell how to do things across
repos/projects and move stuff around… and in my frustration i just randomly
and quickly created and closed stuff, didn’t think about the impact and I’m
sorry for the curfuffle I created in the process


-----

Michael E. Meyers, Managing Director - Tag1.com <https://tag1.com/>

Mobile: +1-917-402-8263 Twitter <http://twitter.com/michaelemeyers>,
LinkedIn <http://www.linkedin.com/in/michaelemeyers>

*<Tag1> Development & Infrastructure *


To easily schedule a meeting with me: https://calendly.com/michaelemeyers


*Tag1 blog* <https://tag1.com/blog>* & **Tag1TeamTalks Podcast*
<https://tag1.com/Tag1TeamTalks>
